# -*- coding: utf-8 -*-
"""Codingan Dasboard Nora

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qzw1Nb66M8rvT8clxAkoFjoxdA8wpxbv
"""

# =========================================================
# APLIKASI ANALISIS PERFORMA SISWA
# (RECODE – COLAB & STREAMLIT FRIENDLY)
# =========================================================

!pip install streamlit
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# =========================================================
# KONFIGURASI STREAMLIT
# =========================================================
st.set_page_config(
    page_title="Analisis Performa Siswa",
    layout="wide"
)

st.title("📊 Analisis Performa Siswa")
st.caption("Evaluasi hasil simulasi 50 siswa berdasarkan 20 indikator soal")

# =========================================================
# FUNGSI BANTU
# =========================================================
def baca_data(path):
    df = pd.read_excel(path)
    return df.apply(pd.to_numeric, errors="coerce")

def klasifikasi_capaian(persen):
    if persen >= 80:
        return "Sangat Baik"
    elif persen >= 65:
        return "Baik"
    elif persen >= 50:
        return "Cukup"
    else:
        return "Kurang"

# =========================================================
# LOAD DATA (DATA SAMA)
# =========================================================
FILE_DATA = "data_simulasi_50_siswa_20_soal.xlsx"

try:
    data = baca_data(FILE_DATA)
except Exception as e:
    st.error(f"Gagal membaca data: {e}")
    st.stop()

# =========================================================
# RINGKASAN KINERJA
# =========================================================
st.subheader("📌 Ringkasan Kinerja")

if 'data' in globals(): # Check if 'data' is defined in the global scope
    rata_per_indikator = data.mean()
    rata_total = rata_per_indikator.mean()
    persentase_capaian = (rata_total / 4) * 100

    c1, c2, c3 = st.columns(3)
    c1.metric("Rata-rata Skor", f"{rata_total:.2f}")
    c2.metric("Kategori", klasifikasi_capaian(persentase_capaian))
    c3.metric("Jumlah Siswa", data.shape[0])
else:
    st.error("Data belum dimuat. Pastikan file 'data_simulasi_50_siswa_20_soal.xlsx' tersedia dan sel sebelumnya sudah dijalankan.")
    st.stop()

st.divider()

# =========================================================
# ANALISIS GAP
# =========================================================
st.subheader("🎯 Analisis GAP Soal")

if 'rata_per_indikator' in globals(): # Check if 'rata_per_indikator' is defined
    gap_nilai = 4 - rata_per_indikator
    soal_kritis = gap_nilai.idxmax()

    fig_gap, ax = plt.subplots(figsize=(12, 4))
    ax.plot(gap_nilai.index, gap_nilai.values, marker="o")
    ax.set_ylabel("Nilai GAP")
    ax.set_title("GAP Skor Ideal vs Aktual")
    plt.xticks(rotation=45)

    st.pyplot(fig_gap)

    st.info(
        f"Soal yang paling membutuhkan perhatian: **{soal_kritis}** "
        f"(GAP = {gap_nilai.max():.2f})"
    )
else:
    st.error("Variabel 'rata_per_indikator' belum terdefinisi. Pastikan data berhasil dimuat dan sel sebelumnya sudah dijalankan.")
    st.stop()

st.divider()

# =========================================================
# ANALISIS KORELASI
# =========================================================
st.subheader("🔗 Hubungan Antar Soal")

if 'data' in globals(): # Check if 'data' is defined
    korelasi = data.corr()

    fig_corr, ax = plt.subplots(figsize=(9, 7))
    cax = ax.imshow(korelasi, cmap="coolwarm", vmin=-1, vmax=1)
    fig_corr.colorbar(cax)

    ax.set_xticks(range(len(korelasi.columns)))
    ax.set_yticks(range(len(korelasi.columns)))
    ax.set_xticklabels(korelasi.columns, rotation=90)
    ax.set_yticklabels(korelasi.columns)
    ax.set_title("Heatmap Korelasi Pearson")

    st.pyplot(fig_corr)
else:
    st.error("Data belum dimuat. Pastikan file 'data_simulasi_50_siswa_20_soal.xlsx' tersedia dan sel sebelumnya sudah dijalankan.")
    st.stop()

st.divider()

# =========================================================
# ANALISIS REGRESI
# =========================================================
st.subheader("⚖️ Analisis Regresi Linear")

if 'data' in globals(): # Check if 'data' is defined
    X = sm.add_constant(data.iloc[:, :-1])   # Soal 1–19
    y = data.iloc[:, -1]                     # Soal 20

    reg_model = sm.OLS(y, X, missing="drop").fit()

    st.metric("Nilai R-Squared", f"{reg_model.rsquared:.3f}")

    top_faktor = (
        reg_model.params[1:]
        .sort_values(ascending=False)
        .head(5)
    )

    st.write("🔝 Faktor paling berpengaruh terhadap Soal 20:")
    st.dataframe(top_faktor.to_frame("Koefisien"))
else:
    st.error("Data belum dimuat. Pastikan file 'data_simulasi_50_siswa_20_soal.xlsx' tersedia dan sel sebelumnya sudah dijalankan.")
    st.stop()

st.divider()

# =========================================================
# SEGMENTASI SISWA
# =========================================================
st.subheader("👥 Segmentasi Kemampuan Siswa")

if 'data' in globals(): # Check if 'data' is defined
    scaler = StandardScaler()
    data_scaled = scaler.fit_transform(data.fillna(0))

    model_cluster = KMeans(n_clusters=3, random_state=1, n_init=10)
    label_cluster = model_cluster.fit_predict(data_scaled)

    hasil_cluster = data.copy()
    hasil_cluster["Cluster"] = label_cluster

    rata_cluster = hasil_cluster.groupby("Cluster").mean().mean(axis=1)
    urutan = rata_cluster.sort_values(ascending=False).index

    label_segment = {
        urutan[0]: "Mahir",
        urutan[1]: "Menengah",
        urutan[2]: "Dasar"
    }

    hasil_cluster["Segment"] = hasil_cluster["Cluster"].map(label_segment)

    st.write("Distribusi segmentasi siswa:")
    st.dataframe(hasil_cluster["Segment"].value_counts().to_frame("Jumlah"))

    st.success("✅ Analisis selesai dan aplikasi siap digunakan")
else:
    st.error("Data belum dimuat. Pastikan file 'data_simulasi_50_siswa_20_soal.xlsx' tersedia dan sel sebelumnya sudah dijalankan.")
    st.stop()